# FILE: docker-compose.yml  (version satırına gerek yok)
services:
  mongo:
    image: mongo:7
    container_name: mk_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      # mongosh + grep ile daha stabil
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.runCommand({ ping: 1 }).ok\" | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mk_api
    # NOT: Eğer server/.env.docker içinde MONGODB_URI (Atlas) varsa
    # ya burayı kullan (mongo servisini kaldır) ya da aşağıdaki local URI'yı kullan.
    # Karışmaması için ya env_file'dan MONGODB_URI'yi sil, ya da env_file satırını kaldır.
    # env_file:
    #   - ./server/.env.docker
    environment:
      HOST: 0.0.0.0
      PORT: 4000
      # Yerel Mongo kullanıyorsan:
      MONGODB_URI: mongodb://mongo:27017/medknowledge?directConnection=true&serverSelectionTimeoutMS=10000
      CORS_ORIGIN: http://localhost:3000
      VIDEO_ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:4000/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 10

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: "http://localhost:4000" # tarayıcı için (client)
    container_name: mk_web
    environment:
      NODE_ENV: production
      PORT: 3000
      BACKEND_URL: http://api:4000                      # server-side fetch için (SSR/route.ts)
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started
    restart: unless-stopped

volumes:
  mongo_data:
